[package]
name = "llama"
version = "0.1.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1"
llvm-sys = {version = "90", features=["no-llvm-linking"]}

[build-dependencies]

[workspace]
members = [
  "build",
  "wasm"
]
