[package]
name = "llama-wasm"
version = "0.1.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
thiserror = "1"
llama = {path = ".."}
wasmtime = {version = "0.12", optional = true}

[features]
default = ["wasmtime"]
