name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install llvm-9-dev llvm-9-tools && sudo ln -sf /usr/bin/llvm-config-9 /usr/bin/llvm-config
    - name: Run tests
      run: cargo test --verbose --all-features
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: brew install llvm && ln -sf /usr/local/opt/llvm/bin/llvm-config /usr/local/bin/llvm-config
    - name: Run tests
      run: cargo test --verbose --all-features
  all_linux_nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install llvm-9-dev llvm-9-tools && sudo ln -sf /usr/bin/llvm-config-9 /usr/bin/llvm-config
    - name: Nightly
      run: rustup toolchain install nightly
    - name: Run tests
      run: cargo +nightly test --verbose --all-features --all
  all_macos_nightly:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: brew install llvm && ln -sf /usr/local/opt/llvm/bin/llvm-config /usr/local/bin/llvm-config
    - name: Nightly
      run: rustup toolchain install nightly
    - name: Run tests
      run: cargo +nightly test --verbose --all-features --all
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install llvm-9-dev llvm-9-tools && sudo ln -sf /usr/bin/llvm-config-9 /usr/bin/llvm-config
    -name: Nightly
      run: rustup toolchain install nightly
    - name: Run tests
      run: cargo +nightly clippy --all-features --all


