name: rustdoc
on:
  push:
   branches:
   - master

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      CARGO_INCREMENTAL: 0

    steps:
    - name: Checkout repository and install dependencies
      uses: actions/checkout@v2
      run: sudo apt install llvm-9-dev libclang-9-dev llvm-9-tools && sudo ln -sf /usr/bin/llvm-config-9 /usr/bin/llvm-config

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rustfmt, rust-src

    - name: Build Documentation
      run: cargo doc --all --no-deps

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
